apiVersion: v1
kind: Pod
metadata:
  name: number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh","-c"]
    args: ["for i in $(seq 1 10); do echo $i >> /data/number1to10.txt; done; tail -f /dev/null"]
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /data
      type: DirectoryOrCreate