apiVersion: v1
kind: PersistentVolume
metadata:
  name: random-numbers-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # path on the host machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: random-numbers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
