apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data"
    type: DirectoryOrCreate
